"""Criação das tabelas

Revision ID: dcca834d3f61
Revises: 
Create Date: 2025-04-25 14:53:42.316973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcca834d3f61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('termometro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setor', sa.String(length=100), nullable=True),
    sa.Column('equipamento', sa.String(length=100), nullable=True),
    sa.Column('especificacao', sa.String(length=100), nullable=True),
    sa.Column('identificacao', sa.String(length=50), nullable=True),
    sa.Column('padrao_identificacao', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('temperatura_atual', sa.Float(), nullable=True),
    sa.Column('temperatura_max', sa.Float(), nullable=True),
    sa.Column('temperatura_min', sa.Float(), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('termometro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['termometro_id'], ['termometro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verificacao')
    op.drop_table('termometro')
    # ### end Alembic commands ###
